---
- name: Download K3s install script
  get_url:
    url: https://get.k3s.io
    dest: /tmp/k3s.sh
    mode: '0755'

- name: Install K3s Agent (Worker Node)
  shell: |
    INSTALL_K3S_VERSION="{{ k3s_version }}" K3S_TOKEN="{{ k3s_token }}" K3S_URL="{{ k3s_api_server_endpoint }}" /tmp/k3s.sh agent \
      --node-ip {{ ansible_host }} \
      --resolv-conf /run/systemd/resolve/resolv.conf
